Add Application Insights to the project templates
aspnet/Templates pull request #755
Opened 2016-12-14 23:42 UTC by pakrym

2016-12-14 23:42 UTC, dnfclas commented
Hi __@pakrym__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by .NET Foundation and real humans are currently evaluating your PR.</p>

TTYL, DNFBOT;

2016-12-15 00:12 UTC, phenning requested changes

2016-12-15 00:12 UTC, phenning commented on src/BaseTemplates/StarterWeb/StarterWeb.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
Alphabetize

2016-12-15 00:12 UTC, phenning commented on src/BaseTemplates/EmptyWeb/EmptyWeb.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
Alphabetize

2016-12-15 00:12 UTC, phenning commented on src/BaseTemplates/WebAPI/WebAPI.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
Alphabetize

2016-12-16 22:19 UTC, mlorbetske commented on src/BaseTemplates/StarterWeb/StarterWeb.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
This version will need to be parameterized, right @phenning?

2016-12-16 22:19 UTC, mlorbetske commented on src/BaseTemplates/WebAPI/WebAPI.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
This one too

2016-12-17 17:02 UTC, mlorbetske approved these changes

2016-12-19 17:00 UTC, merged